Fix coverage commits

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -344,6 +344,19 @@ runs:
             echo "::error::Hypothesis Helm requires a Linux or macOS runner."
             exit 1
         fi
+        if [[ "$RUNNER_OS" == "macOS" ]]; then
+            if [[ ! -x "$(brew --prefix)/opt/bash/bin/bash" ]]; then
+                brew install bash
+            fi
+            echo "$(brew --prefix bash)/bin" >>"$GITHUB_PATH"
+        fi
+    - name: Check Bash version
+      shell: bash
+      run: |
+        if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4))); then
+            echo '::error::Hypothesis Helm requires Bash 4.4 or newer.'
+            exit 1
+        fi
     - uses: actions/setup-python@v7
       with:
         python-version: ${{ inputs.python-version }}
